-- Create the analyses table to store Learning MRI results
CREATE TABLE analyses (
  id TEXT PRIMARY KEY, -- The analysis-1234 ID generated by the backend
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  student_id TEXT NOT NULL,
  status TEXT NOT NULL, -- e.g., 'completed', 'failed'
  subject_detected TEXT NOT NULL,
  score_obtained TEXT, -- stored as text e.g., '31' or numeric depending on future need. For now, matching UI.
  score_total TEXT, -- e.g., '40'
  model_used TEXT NOT NULL,
  processing_duration_ms INTEGER,
  analysis_data JSONB NOT NULL -- The complete Zod-validated LearningMRI JSON
);

-- Index for querying by student
CREATE INDEX idx_analyses_student_id ON analyses(student_id);

-- Index for ordering by recency
CREATE INDEX idx_analyses_created_at ON analyses(created_at DESC);
